### ISSUE TITLE
“3.1 度量空间与压缩映射”是想说啥？

### ISSUE THREAD

**Issue by A-Pai** [Anesck/M-D-R_learning_notes#2]
你的 MD笔记做的很好，很精美！很受益，谢谢！还想进一步交流：
肖智清强化学习书“3.1 度量空间与压缩映射”讲到了不动点等定理，但是这一节的总体目的是什么，没有讲清楚。
我感觉到最重要的是要证明最优价值函数的存在、唯一
唯一性可以从压缩映射得到，怎么知道这个不动点就是最优的？

**Comment by Anesck** [comment]
这一节要证明的是期望算子和最优算子是某度量空间上的压缩映射，这样可以就通过不动点定理及其求取方法求得策略价值和最优价值
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anesck/M-D-R_learning_notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午4:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Anesck/M-D-R_learning_notes] “3.1 度量空间与压缩映射”是想说啥？ (#2)





 
你的 MD笔记做的很好，很精美！很受益，谢谢！还想进一步交流：
 肖智清强化学习书“3.1 度量空间与压缩映射”讲到了不动点等定理，但是这一节的总体目的是什么，没有讲清楚。
 我感觉到最重要的是要证明最优价值函数的存在、唯一
 唯一性可以从压缩映射得到，怎么知道这个不动点就是最优的？

**Comment by A-Pai** [comment]
> 这一节要证明的是期望算子和最优算子是某度量空间上的压缩映射，这样可以就通过不动点定理及其求取方法求得策略价值和最优价值 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Anesck/M-D-R_learning_notes" ***@***.***&gt;; 发送时间:&nbsp;2021年7月27日(星期二) 下午4:29 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Anesck/M-D-R_learning_notes] “3.1 度量空间与压缩映射”是想说啥？ (#2) 你的 MD笔记做的很好，很精美！很受益，谢谢！还想进一步交流： 肖智清强化学习书“3.1 度量空间与压缩映射”讲到了不动点等定理，但是这一节的总体目的是什么，没有讲清楚。 我感觉到最重要的是要证明最优价值函数的存在、唯一 唯一性可以从压缩映射得到，怎么知道这个不动点就是最优的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

---应该从理论上首先证明最优价值函数存在，之后才是设计算法找到

**Comment by Anesck** [comment]
那是第二章的内容


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anesck/M-D-R_learning_notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anesck/M-D-R_learning_notes] “3.1 度量空间与压缩映射”是想说啥？ (#2)





  
这一节要证明的是期望算子和最优算子是某度量空间上的压缩映射，这样可以就通过不动点定理及其求取方法求得策略价值和最优价值 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Anesck/M-D-R_learning_notes" @.&gt;; 发送时间:&nbsp;2021年7月27日(星期二) 下午4:29 @.&gt;; @.***&gt;; 主题:&nbsp;[Anesck/M-D-R_learning_notes] “3.1 度量空间与压缩映射”是想说啥？ (#2) 你的 MD笔记做的很好，很精美！很受益，谢谢！还想进一步交流： 肖智清强化学习书“3.1 度量空间与压缩映射”讲到了不动点等定理，但是这一节的总体目的是什么，没有讲清楚。 我感觉到最重要的是要证明最优价值函数的存在、唯一 唯一性可以从压缩映射得到，怎么知道这个不动点就是最优的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
---应该从理论上首先证明最优价值函数存在，之后才是设计算法找到

**Comment by A-Pai** [comment]
第二章中讲的了这个？--严格的数学证明

**Comment by Anesck** [comment]
这不是证明出来的，第二章中给出了定义，第三章证明这些定义的价值函数可以通过迭代方法求得




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anesck/M-D-R_learning_notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 晚上8:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anesck/M-D-R_learning_notes] “3.1 度量空间与压缩映射”是想说啥？ (#2)





 
第二章中讲的了这个？--严格的数学证明

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  LI,Gang
